schema: ./libs/composedb/lib/schema.graphql
extensions:
  endpoints:
    Default GraphQL Endpoint:
      url: http://localhost:5001/graphql
      headers:
        user-agent: JS GraphQL
      introspect: true
